
projects:
  app:
    schemaPath: "./src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:50000"
  prisma:
    schemaPath: "./src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
    # schemaPath: "./generated/prisma.schema"
